---
functional:
 - Сайт должен иметь возможность двум игрокам соревноваться друг с другом в решении задач по программированию
 - Сайт должен иметь возможность двум игрокам видеть написание кода друг у друга
 - Сайт должен иметь возможность играть с ботом
 - Сайт должен иметь возможность видеть свой рейтинг и других игроков
 - Сайт должен иметь возможность изменения синтаксиса языка программирования в редакторе
 - Сайт должен иметь возможность игрокам участвовать в турнирах
 - Сайт должен иметь возможность игрокам просматривать результат завершеннных игр
 - Сайт должен иметь возможность игрокам видеть результаты тестов кода во время игры
 - Сайт должен иметь внутриигровой чат
 - Сайт должен иметь возможность создавать игры
 - Сайт должен иметь возможность присоединяться к играм
 - При создании игры можно выбирать сложность
 - При создании игры можно задавать ограничение по времени
 - При создании игры можно выбирать задачу для решения
 - При создании игры задачи можно выбирать по тегам
 - Участники игры имеют возможность сдаться
 - Участники игры имеют возможность проверить своё решение на соотвествие требованиям выбранной задачи
non-functional:
 - Сайт должен иметь мобильную версию
 - Для создания учетной записи необходим никнейм, email, пароль, подтверждение пароля
 - Никнейм пользователя может состоять только из латинских букв
 - Никнейм пользователя должен начинаться с латинской буквы
 - Допустимая длина никнейма от 3 до 16 символов
 - Для входа в учетную запись необходим email и пароль
 - Существует возможность входа в учетную запись через аккаунт github
 - Существует возможность входа в учетную запись через через аккаунт discord
 - Пользователь имеет возможность изменить звук алертов
 - Пользователь имеет возможность изменять уровень громкости алертов
 - Пользователь имеет возможность изменять язык программирования, выбранный по умолчанию
implicit:
 - Сайт должен иметь возможность авторизации
 - Сайт должен иметь возможность создания учетной записи
 - Сайт должен иметь возможность выхода из учетной записи
 - Сайт должен быть способен обрабатывать большое количество трафика
 - Сайт должен обеспечивать безопасность данных пользователя
 - Сайт должен быть протестирован на совместимость с последними версиями браузеров
 - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
