---
functional:
 - Сайт должен иметь возможность двум игрокам соревноваться друг с другом в решении задач по программированию
 - Сайт должен иметь возможность двум игрокам видеть написание кода друг у друга
 - Сайт должен иметь возможность играть с ботом
 - Сайт должен иметь возможность видеть свой рейтинг и других игроков
 - Сайт должен иметь возможность изменения синтаксиса языка программирования в редакторе
 - Сайт должен иметь возможность игрокам участвовать в турнирах
 - Сайт должен иметь возможность игрокам просматривать результат завершеннных игр
 - Сайт должен иметь возможность игрокам видеть результаты тестов кода во время игры
 - Сайт должен иметь внутриигровой чат
 - Сайт должен иметь возможность создавать игры
 - Сайт должен иметь возможность присоединяться к играм
 - При создании игры можно выбирать сложность
 - При создании игры можно задавать ограничение по времени
 - При создании игры можно выбирать задачу для решения
 - При создании игры можно выбирать теги
non-functional:
 - Сайт должен иметь мобильную версию
 - Сайт должен быть способен обрабатывать большое количество трафика
 - Сайт должен обеспечивать безопасность данных пользователя
 - Сайт должен быть протестирован на совместимость с последними версиями браузеров
 - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
 - Для входа в учетную запись необходим email и пароль
 - Есть возможность входа в учетную запись через аккаунт github
 - Есть возможность входа в учетную запись через через аккаунт discord
implicit:
 - Сайт должен иметь возможность авторизации
 - Сайт должен иметь возможность создания учетной записи
