---
functional:
 - Проект должен иметь возможность двум игрокам соревноваться друг с другом
 - Проект должен иметь возможность двум игрокам видеть написание кода друг у друга
 - Проект должен иметь возможность играть с ботом
 - Проект должен иметь возможность авторизации
 - Проект должен иметь возможность создания учетной записи
 - Проект должен иметь возможность видеть свой рейтинг и других игроков
 - Сайт должен иметь возможность изменения синтаксиса языка в редакторе
non-functional:
 - Проект должен иметь мобильную версию
 - Проект должен быть способен обрабатывать большое количество трафика
 - Проект должен обеспечивать безопасность данных пользователя
 - Веб-приложение должно 
implicit:
 - Проект должен иметь мобильную версию
 - Проект должен быть способен обрабатывать большое количество трафика
 - Проект должен обеспечивать безопасность данных пользователя
 - Веб-приложение должно 
