---
functional:
 - Сайт должен иметь возможность двум игрокам соревноваться друг с другом
 - Сайт должен иметь возможность двум игрокам видеть написание кода друг у друга
 - Сайт должен иметь возможность играть с ботом
 - Сайт должен иметь возможность авторизации
 - Сайт должен иметь возможность создания учетной записи
 - Сайт должен иметь возможность видеть свой рейтинг и других игроков
 - Сайт должен иметь возможность изменения синтаксиса языка в редакторе
 - Сайт должен иметь возможность игрокам участвовать в турнирах
 - Сайт должен иметь возможность игрокам просматривать результат завершеннных игр
non-functional:
 - Сайт должен иметь мобильную версию
 - Сайт должен быть способен обрабатывать большое количество трафика
 - Сайт должен обеспечивать безопасность данных пользователя
 - Сайт должен быть протестирован на совместимость с последними версиями браузеров
 - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
 - Сайт должен иметь мобильную версию
 - Сайт должен быть способен обрабатывать большое количество трафика
 - Сайт должен обеспечивать безопасность данных пользователя
 - Сайт должен быть протестирован на совместимость с последними версиями браузеров
 - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
